// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// projection_vector_directions
arma::rowvec projection_vector_directions(arma::vec xxT, arma::mat directions);
RcppExport SEXP DepthDescent_projection_vector_directions(SEXP xxTSEXP, SEXP directionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xxT(xxTSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type directions(directionsSEXP);
    rcpp_result_gen = Rcpp::wrap(projection_vector_directions(xxT, directions));
    return rcpp_result_gen;
END_RCPP
}
// projection_directions
arma::mat projection_directions(arma::mat XXT, arma::mat directions);
RcppExport SEXP DepthDescent_projection_directions(SEXP XXTSEXP, SEXP directionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type XXT(XXTSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type directions(directionsSEXP);
    rcpp_result_gen = Rcpp::wrap(projection_directions(XXT, directions));
    return rcpp_result_gen;
END_RCPP
}
// projection_a_direction
arma::rowvec projection_a_direction(arma::mat XXT, arma::vec adirection);
RcppExport SEXP DepthDescent_projection_a_direction(SEXP XXTSEXP, SEXP adirectionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type XXT(XXTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type adirection(adirectionSEXP);
    rcpp_result_gen = Rcpp::wrap(projection_a_direction(XXT, adirection));
    return rcpp_result_gen;
END_RCPP
}
// find_depth_on_u_move
Rcpp::List find_depth_on_u_move(arma::vec u_move, arma::mat joined_Minter);
RcppExport SEXP DepthDescent_find_depth_on_u_move(SEXP u_moveSEXP, SEXP joined_MinterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type u_move(u_moveSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type joined_Minter(joined_MinterSEXP);
    rcpp_result_gen = Rcpp::wrap(find_depth_on_u_move(u_move, joined_Minter));
    return rcpp_result_gen;
END_RCPP
}
// find_depth_on_multiple_u_move
Rcpp::List find_depth_on_multiple_u_move(arma::mat u_min, arma::mat joined_Minter);
RcppExport SEXP DepthDescent_find_depth_on_multiple_u_move(SEXP u_minSEXP, SEXP joined_MinterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type u_min(u_minSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type joined_Minter(joined_MinterSEXP);
    rcpp_result_gen = Rcpp::wrap(find_depth_on_multiple_u_move(u_min, joined_Minter));
    return rcpp_result_gen;
END_RCPP
}
// find_depth_on_all_directions
Rcpp::List find_depth_on_all_directions(arma::mat M, arma::mat projectto, arma::mat directions);
RcppExport SEXP DepthDescent_find_depth_on_all_directions(SEXP MSEXP, SEXP projecttoSEXP, SEXP directionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type projectto(projecttoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type directions(directionsSEXP);
    rcpp_result_gen = Rcpp::wrap(find_depth_on_all_directions(M, projectto, directions));
    return rcpp_result_gen;
END_RCPP
}
// move_a_step
Rcpp::List move_a_step(arma::uvec depth_on_u_move, int Minter_depth_u_move, arma::vec u_move, arma::mat Minter, arma::rowvec project_to_u_move);
RcppExport SEXP DepthDescent_move_a_step(SEXP depth_on_u_moveSEXP, SEXP Minter_depth_u_moveSEXP, SEXP u_moveSEXP, SEXP MinterSEXP, SEXP project_to_u_moveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type depth_on_u_move(depth_on_u_moveSEXP);
    Rcpp::traits::input_parameter< int >::type Minter_depth_u_move(Minter_depth_u_moveSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type u_move(u_moveSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Minter(MinterSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type project_to_u_move(project_to_u_moveSEXP);
    rcpp_result_gen = Rcpp::wrap(move_a_step(depth_on_u_move, Minter_depth_u_move, u_move, Minter, project_to_u_move));
    return rcpp_result_gen;
END_RCPP
}
// descent_algorithm_matrix_depth
Rcpp::List descent_algorithm_matrix_depth(arma::mat XXT, arma::vec Minitial, arma::mat directions, int ntry, int step_check, bool print);
RcppExport SEXP DepthDescent_descent_algorithm_matrix_depth(SEXP XXTSEXP, SEXP MinitialSEXP, SEXP directionsSEXP, SEXP ntrySEXP, SEXP step_checkSEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type XXT(XXTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Minitial(MinitialSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type directions(directionsSEXP);
    Rcpp::traits::input_parameter< int >::type ntry(ntrySEXP);
    Rcpp::traits::input_parameter< int >::type step_check(step_checkSEXP);
    Rcpp::traits::input_parameter< bool >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(descent_algorithm_matrix_depth(XXT, Minitial, directions, ntry, step_check, print));
    return rcpp_result_gen;
END_RCPP
}
// banding_a_matrix
arma::mat banding_a_matrix(arma::mat M, int k);
RcppExport SEXP DepthDescent_banding_a_matrix(SEXP MSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(banding_a_matrix(M, k));
    return rcpp_result_gen;
END_RCPP
}
// banding
arma::mat banding(arma::vec U, int k);
RcppExport SEXP DepthDescent_banding(SEXP USEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(banding(U, k));
    return rcpp_result_gen;
END_RCPP
}
// move_a_step_with_banding
Rcpp::List move_a_step_with_banding(arma::uvec depth_on_u_move, int Minter_depth_u_move, arma::vec u_move, arma::mat Minter, arma::rowvec project_to_u_move, int k);
RcppExport SEXP DepthDescent_move_a_step_with_banding(SEXP depth_on_u_moveSEXP, SEXP Minter_depth_u_moveSEXP, SEXP u_moveSEXP, SEXP MinterSEXP, SEXP project_to_u_moveSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type depth_on_u_move(depth_on_u_moveSEXP);
    Rcpp::traits::input_parameter< int >::type Minter_depth_u_move(Minter_depth_u_moveSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type u_move(u_moveSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Minter(MinterSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type project_to_u_move(project_to_u_moveSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(move_a_step_with_banding(depth_on_u_move, Minter_depth_u_move, u_move, Minter, project_to_u_move, k));
    return rcpp_result_gen;
END_RCPP
}
// descent_algorithm_matrix_depth_bandable
Rcpp::List descent_algorithm_matrix_depth_bandable(arma::mat XXT, arma::vec Minitial, arma::mat directions, int ntry, int step_check, int band);
RcppExport SEXP DepthDescent_descent_algorithm_matrix_depth_bandable(SEXP XXTSEXP, SEXP MinitialSEXP, SEXP directionsSEXP, SEXP ntrySEXP, SEXP step_checkSEXP, SEXP bandSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type XXT(XXTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Minitial(MinitialSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type directions(directionsSEXP);
    Rcpp::traits::input_parameter< int >::type ntry(ntrySEXP);
    Rcpp::traits::input_parameter< int >::type step_check(step_checkSEXP);
    Rcpp::traits::input_parameter< int >::type band(bandSEXP);
    rcpp_result_gen = Rcpp::wrap(descent_algorithm_matrix_depth_bandable(XXT, Minitial, directions, ntry, step_check, band));
    return rcpp_result_gen;
END_RCPP
}
