# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

projection_vector_directions <- function(xxT, directions) {
    .Call('DepthDescent_projection_vector_directions', PACKAGE = 'DepthDescent', xxT, directions)
}

projection_directions <- function(XXT, directions) {
    .Call('DepthDescent_projection_directions', PACKAGE = 'DepthDescent', XXT, directions)
}

projection_a_direction <- function(XXT, adirection) {
    .Call('DepthDescent_projection_a_direction', PACKAGE = 'DepthDescent', XXT, adirection)
}

find_depth_on_u_move <- function(u_move, joined_Minter) {
    .Call('DepthDescent_find_depth_on_u_move', PACKAGE = 'DepthDescent', u_move, joined_Minter)
}

find_depth_on_multiple_u_move <- function(u_min, joined_Minter) {
    .Call('DepthDescent_find_depth_on_multiple_u_move', PACKAGE = 'DepthDescent', u_min, joined_Minter)
}

find_depth_on_all_directions <- function(M, projectto, directions) {
    .Call('DepthDescent_find_depth_on_all_directions', PACKAGE = 'DepthDescent', M, projectto, directions)
}

move_a_step <- function(depth_on_u_move, Minter_depth_u_move, u_move, Minter, project_to_u_move) {
    .Call('DepthDescent_move_a_step', PACKAGE = 'DepthDescent', depth_on_u_move, Minter_depth_u_move, u_move, Minter, project_to_u_move)
}

descent_algorithm_matrix_depth <- function(XXT, Minitial, directions, ntry, step_check, print) {
    .Call('DepthDescent_descent_algorithm_matrix_depth', PACKAGE = 'DepthDescent', XXT, Minitial, directions, ntry, step_check, print)
}

banding_a_matrix <- function(M, k) {
    .Call('DepthDescent_banding_a_matrix', PACKAGE = 'DepthDescent', M, k)
}

banding <- function(U, k) {
    .Call('DepthDescent_banding', PACKAGE = 'DepthDescent', U, k)
}

move_a_step_with_banding <- function(depth_on_u_move, Minter_depth_u_move, u_move, Minter, project_to_u_move, k) {
    .Call('DepthDescent_move_a_step_with_banding', PACKAGE = 'DepthDescent', depth_on_u_move, Minter_depth_u_move, u_move, Minter, project_to_u_move, k)
}

descent_algorithm_matrix_depth_bandable <- function(XXT, Minitial, directions, ntry, step_check, band) {
    .Call('DepthDescent_descent_algorithm_matrix_depth_bandable', PACKAGE = 'DepthDescent', XXT, Minitial, directions, ntry, step_check, band)
}

